
trigger:
- master

variables:
  DOTNET_SDK_VERSION: '2.1.401'

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
  inputs:
    version: '$(DOTNET_SDK_VERSION)'

- task: PowerShell@2
  targetType: filePath
  filePath: ./build.ps1  

- task: CopyFiles@2
  displayName: 'Copy generated content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/output'
    contents: '**\*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/output
    cleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy deployment content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/deployment'
    contents: '**\*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/deployment
    cleanTargetFolder: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'