trigger:
-master

variables:
  DOTNET_SDK_VERSION: '2.1.401'

pool: 
  vmImage: 'VS2017-Win2016'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
  inputs: 
    version: '$(DOTNET_SDK_VERSION)'

- powershell: ./build.ps1
  displayName: 'Execute Cake Powershell Bootstrapper'

- task: CopyFiles@2
  displayName: 'Copy generated content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/output'
    contents: '**\*'
    targetFolder: $(Build.ArtifactsStagingDirectory)/output
    cleanTargetFolder: true
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'